### ISSUE TITLE
CUSA00265 - Minecraft

### ISSUE THREAD

**Issue by Missake212** [shadps4-compatibility/shadps4-game-compatibility#22]
### Game Name

Minecraft

### Game code

CUSA00265

### Game version

v02.78

### Used emulator's version (only major released versions are acceptable)

v0.6.0

### Current status

Nothing

### Operating System

Windows

### Error

[Core] <Error> stubs.cpp:CommonStub:42: Stub: sendto (nid: oBr313PppNE) called, returning zero to 0x906119bfd
[Core] <Error> stubs.cpp:CommonStub:42: Stub: sendto (nid: oBr313PppNE) called, returning zero to 0x906119bfd

### Description

Black screen that hangs indefinitely.

### Log File

[shad_log.zip](https://github.com/user-attachments/files/19233610/shad_log.zip)

**Comment by Missake212** [comment]
On 0.7.0, we can now hear the title music, but it still hangs indefinitely.

[CUSA00265.zip](https://github.com/user-attachments/files/19406332/CUSA00265.zip)

**Comment by brad0demx** [comment]
### release 0.7.0 
### Game version 1.00


you can get to menus and ingame with some rendering issues. 
UI tends to be invisible, overlap other UI elements, or be in the wrong spot on the screen. The UI is functional and loading in game it has solid FPS and visuals, aside from the invisible and missplaced UI. 

There is a significant amount of input delay when playing with a controller. 


![Image](https://github.com/user-attachments/assets/fec33c3b-ecd9-4a95-942e-e57c6f908051)

![Image](https://github.com/user-attachments/assets/fa6ed7ce-8be4-4b55-8576-21fe940b8ccc)

[shad_log.txt](https://github.com/user-attachments/files/19492104/shad_log.txt)

**Comment by brad0demx** [comment]
### Release 0.7.0
### Game version 1.95

UI is significantly improved, however input delay is still there. There are some performance issues in this version, dropping to mid 30s at the beginning. Though this could be due to the map being more complex in this version of the tutorial world. 

Saving the game does not work well, if at all. Attempting to load a save can softlock the game

![Image](https://github.com/user-attachments/assets/025a5f30-af25-428d-8cd7-f9fd1fe7400a)

![Image](https://github.com/user-attachments/assets/bb8877ac-5d70-4ad3-b776-551894f10ec1)

![Image](https://github.com/user-attachments/assets/22df1f04-6eea-4d7b-900b-3ec9bb0d7fa3)

[shad_log.txt](https://github.com/user-attachments/files/19492477/shad_log.txt)

[Minecraft save data soft lock shad_log.txt](https://github.com/user-attachments/files/19492478/Minecraft.save.data.soft.lock.shad_log.txt)

**Comment by Missake212** [comment]
No changes for both v01.00 and v02.78

[CUSA00265v1.00.log](https://github.com/user-attachments/files/19872466/CUSA00265v1.00.log)

[CUSA00265v2.78.log.zip](https://github.com/user-attachments/files/19872477/CUSA00265v2.78.log.zip)

**Comment by brad0demx** [comment]
### Game version 1.95
### Emulator version 0.8.0 

Same behaviour as previous versions. 

![Image](https://github.com/user-attachments/assets/888e5e2f-60ae-41bb-b3e6-5c3a7616e4c3)

![Image](https://github.com/user-attachments/assets/1598c442-696a-4b0b-9046-1b94d696c004)

![Image](https://github.com/user-attachments/assets/03a53939-3439-4f65-ae24-242664d724bd)

[shad_log.txt](https://github.com/user-attachments/files/19900928/shad_log.txt)

**Comment by Missake212** [comment]
No changes on 0.9.0 for version 1.00 and version 2.78.

[CUSA00265 v1.00.log](https://github.com/user-attachments/files/20399623/CUSA00265.v1.00.log)

[CUSA00265 v2.78.log](https://github.com/user-attachments/files/20399662/CUSA00265.v2.78.log)

**Comment by brad0demx** [comment]
No changes on 0.9.0 for version 1.95. The game still experiences the same performance issues and save issues

![Image](https://github.com/user-attachments/assets/49834821-8d11-4ddf-9fcf-c3247a35785c)

![Image](https://github.com/user-attachments/assets/bca72023-c884-4d51-a2ab-6c3211f41db7)

[shad_log.txt](https://github.com/user-attachments/files/20428607/shad_log.txt)

**Comment by Missake212** [comment]
No changes on 0.10.0 for v1.00 and v2.78.

[CUSA00265v1.00.log](https://github.com/user-attachments/files/21110421/CUSA00265.log)

[CUSA00265v2.78.log](https://github.com/user-attachments/files/21110426/CUSA00265.log)

**Comment by W-i-n-7** [comment]
i wish these save issues were fixed

**Comment by bigol83** [comment]
crashes for me soon after reaching ingame without showing any error code

Version   2.92


<img width="1282" height="752" alt="Image" src="https://github.com/user-attachments/assets/0e5bc786-affe-48ff-83ec-35e990775aa3" />
<img width="1282" height="752" alt="Image" src="https://github.com/user-attachments/assets/a43f9d96-976f-4495-828e-171f1d9b1417" />

log

[CUSA00265.zip](https://github.com/user-attachments/files/22402686/CUSA00265.zip)

**Comment by Missake212** [comment]
On 0.11.0, the input lag issue for v1.00 seems to be fixed, no changes other than that, v2.78 now display graphics properly, managed to get in game but crashed with nothing in the log.

<img width="1924" height="1134" alt="Image" src="https://github.com/user-attachments/assets/7b9b6484-5295-4dd2-90b8-9e5f169d7905" />

[CUSA00265 v1.00.log](https://github.com/user-attachments/files/22402979/CUSA00265.v1.00.log)

[CUSA00265 v2.78.log](https://github.com/user-attachments/files/22402938/CUSA00265.v2.78.log)

**Comment by W-i-n-7** [comment]
v0.11.1 WIP 7bd3eb4 --> [shad_log.txt](https://github.com/user-attachments/files/22403878/shad_log.txt)
v0.11.0 --> [shad_log.txt](https://github.com/user-attachments/files/22404276/shad_log.txt)
CUSA00265 version 1.95

<img width="2494" height="1437" alt="Image" src="https://github.com/user-attachments/assets/5491f3dc-c1ce-4f04-a5ca-129095aac903" />

savedata issues, only with saves saved by shadps4 (decrypted saves from my 9.00 work until resaved)

**Comment by W-i-n-7** [comment]
the issue happens because shadps4 saves an empty file as the icon0.png in sce_sys and writes 111 bytes of zeroes to the THUMB(nail) file in the world save data directory
copying these files from a real console's save file will restore the savefile to work again
copying these empty files into a real console and encrypting the save file will have the same crash behaviour as on shadps4

<img width="657" height="281" alt="Image" src="https://github.com/user-attachments/assets/b4edf3f2-a065-4677-ac30-ea9efe12f203" />
<img width="685" height="322" alt="Image" src="https://github.com/user-attachments/assets/409a2b2d-f588-41fe-9684-0eeb3e9020c8" />

EDIT: seems like copying just the THUMB file from a real save will fix the crash

**Comment by Missake212** [comment]
@kalaposfos13  This one needs the ``issues: crashes`` added and the label ``issues: hang`` removed. Also I'm not sure about v1.95 but the input lag issue on 1.00 is resolved for me and it didn't happen on v2.78.

**Comment by Mranonsys** [comment]
0.11.0 [shad_log.txt](https://github.com/user-attachments/files/24792074/shad_log.txt)

v0.13.1 WIP 0d5c5f8
v0.11.0
CUSA00265 version 1.95
Playable but there is a problem with saving, input lag and the the FPS drops after 10 seconds of opening a world.

0.13.1 wip [shad_log.txt](https://github.com/user-attachments/files/24791991/shad_log.txt)

**Comment by Missake212** [comment]
On 0.15.0, v1.00 gets in game and looks playable but I think the input lag is back, I'm not sure, I remember it being really bad back then but now it's like okay, you can feel it when moving the character and the camera the most. V2.78 behave the exact same, I managed to get in game but crashed with nothing in the log (the loading screen had huge performance drops).

[CUSA00265v1.00.log](https://github.com/user-attachments/files/26728588/CUSA00265v1.00.log)

[CUSA00265v2.78.log](https://github.com/user-attachments/files/26728562/CUSA00265v2.78.log)

**Comment by Missake212** [comment]
On 0.16.0, v1.00 crashed for me when I opened the crafting table.

[CUSA00265v1.00.log](https://github.com/user-attachments/files/28505573/CUSA00265.log)

V2.78 got in game pretty good, I managed to play for a bit, I think there's some input issue there too but it's different, it's like you get a really slow stick drift sometimes if you don't move the joystick all the way, I decided to quit and reload my save to make sure it works but I crashed a few seconds in after doing that.

[CUSA00265v2.78.log](https://github.com/user-attachments/files/28505816/CUSA00265.log)

Mentioning this last, I'm not sure if this is a visual issue or not but I'll leave it here, there's a big "wall" like surface all around the map for some reason:

<img width="1924" height="1134" alt="Image" src="https://github.com/user-attachments/assets/9aaa4888-abd5-4fd4-bbe2-92de9c20ca19" />

**Comment by brad0demx** [comment]
The issue you mentioned at the bottom is exclusive to bedrock I think, theres a couple issues which are specific to either version of the game. I was getting an issue in legacy where i had consistent ~1s frame drops. 

Even though that device lost could be a regression im gonna mark it as stable since they're still `ingame`

**Comment by StevenMiller123** [comment]
@Missake212 Just to make sure, do you still have input lag issues with game v1.00?

**Comment by Missake212** [comment]
> [@Missake212](https://github.com/Missake212) Just to make sure, do you still have input lag issues with game v1.00?

Yes

**Comment by StevenMiller123** [comment]
As far as I'm aware, save issues in this title should be fixed now. Is that tag still relevant @brad0demx?

**Comment by brad0demx** [comment]
Last time I checked the input lag issues that I was having a while back were fixed, but I was having other issues with input which seemed to be tied to fact I have a lot of performance issues on that update. The old issue would prevent me from doing stuff like sprinting, or moving the camera in a smooth circle/figure eight which last time I checked isn't the case anymore.

**Comment by RealTriassic** [comment]
Saving seems to be fixed and the game doesn't crash anymore, minor performance issues are still present, but I do not observe any noticeable input lag, running on Fedora 44.

**Comment by Xcissors280** [comment]
Im still having input lag issues on windows

**Comment by jamiessmartbook-gif** [comment]
I am still have save issue on 1.95 after a serten time wenn i close the world ot resets to the stat before so wenn i bracke a block and restart the world the block ist beck wer i took it from

**Comment by mustafa-ahmed-2914** [comment]
there is a bug making you when plug a dualshock controller it just bug and auto click fast and when joining a game with or not a controller the camera just rotates forever btw thats on (v1.00)

**Comment by mustafa-ahmed-2914** [comment]
on 0.18.1 WIP the game works normally and the bug is fixed **ONLY WITH 0.18.1 WIP** without any issues i played a little then saved world and came its saved and i want fo the game to be playbale **although there is fps problem** making the **fps 19**  but when looking to the sky its normal 60fps

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/30eaaf2c-8c24-4067-8939-b870f7c4b6d7" />
